from marshmallow import Schema, fields

class DataSchema(Schema):
    id = fields.String() 
    tensao = fields.String()
    tensao_f1 = fields.String()
    tensao_f2 = fields.String()
    tensao_f3 = fields.String()
    corrente = fields.String() 
    corrente_f1 = fields.String() 
    corrente_f2 = fields.String()
    potencia_ativa = fields.String()
    potencia_ativa_f1 = fields.String()
    potencia_ativa_f2 = fields.String()
    potencia_ativa_f3 = fields.String()
    potencia_reativa = fields.String()
    potencia_reativa_f1 = fields.String()
    potencia_reativa_f2 = fields.String()
    potencia_reativa_f3 = fields.String()
    potencia_aparente = fields.String()
    potencia_aparente_f1 = fields.String()
    potencia_aparente_f2 = fields.String()
    potencia_aparente_f3 = fields.String()
    fp_circuito = fields.String()
    fP_fase1 = fields.String()
    fP_fase2 = fields.String()
    fP_fase3 = fields.String()
    frequencia = fields.String()
    data = fields.String()

